config/routes.rb
Rails.application.routes.draw do
  resources :departments
  devise_for :companies
  # resources :homes
  root to: "departments#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :apartments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :company
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :rif])
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)
    @department.company = current_company

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :company_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!
  
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/departments/_form.html.haml
= form_with(model: department, local: true) do |form|
  - if department.errors.any?
    #error_explanation
      %h2
        = pluralize(department.errors.count, "error")
        prohibited this department from being saved:
      %ul
        - department.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, id: :department_name
  -# .field
  -#   = form.label :company_id
  -#   = form.text_field :company_id, id: :department_company_id
  .actions
    = form.submit

app/views/departments/edit.html.haml
%h1 Editing Department
= render 'form', department: @department
= link_to 'Show', @department
|
= link_to 'Back', departments_path

app/views/departments/index.html.haml
%p#notice= notice
%h1 Departments
%table
  %thead
    %tr
      %th Name
      %th Company
      %th{:colspan => "3"}
  %tbody
    - @departments.each do |department|
      %tr
        %td= department.name
        %td= department.company.name
        %td= link_to 'Show', department
        %td= link_to 'Edit', edit_department_path(department)
        %td= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Department', new_department_path

app/views/departments/new.html.haml
%h1 New Department
= render 'form', department: @department
= link_to 'Back', departments_path

app/views/departments/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @department.name
%p
  %strong Company:
  = @department.company.name
= link_to 'Edit', edit_department_path(@department)
|
= link_to 'Back', departments_path

app/views/homes/_form.html.haml
= form_with(model: home, local: true) do |form|
  - if home.errors.any?
    #error_explanation
      %h2
        = pluralize(home.errors.count, "error")
        prohibited this home from being saved:
      %ul
        - home.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/homes/edit.html.haml
%h1 Editing Home
= render 'form', home: @home
= link_to 'Show', @home
|
= link_to 'Back', homes_path

app/views/homes/index.html.haml
%p#notice= notice
%h1 Homes
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @homes.each do |home|
      %tr
        %td= link_to 'Show', home
        %td= link_to 'Edit', edit_home_path(home)
        %td= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Home', new_home_path

app/views/homes/new.html.haml
%h1 New Home
= render 'form', home: @home
= link_to 'Back', homes_path

app/views/homes/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_home_path(@home)
|
= link_to 'Back', homes_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EmployeeCards
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield